import React from "react";
import image from '../assets/image.png'
import image4 from '../assets/image4.png'
import Ring from '../assets/Ring.png'
import microscope from '../assets/microscope.png'
import Ring2 from '../assets/Ring2.png'
import Rectangle from '../assets/Rectangle.png'
import Footer from "../Componenet/Footer";
import Navbar from "../Componenet/Navbar";
import Design from '../assets/deisgn.png'

export const AboutUs = () => {
    return (
        <>
            <Navbar />
            {/* section...1 */}
            <section className="py-[50px]">

                <div className="container ">

                    <div className="mb-[80px] max-sm:mb-[20px] overflow-hidden ">
                        <h2 className="text-[#D86A37] font-bold text-[40px] leading-[100%] text-center mb-[11px] max-sm:text-[28px]  ">
                            Terms & Conditions</h2><div className="relative flex justify-center"><div className="relative  design">
                                <img alt="Design" className="mx-[50px] relative" src={Design} />
                            </div>
                        </div>
                    </div>

                    <h3 className="text-[19px] mb-5 font-[700]">Introduction</h3>
                    <p className="mb-5">1.1. These Terms and Conditions apply to your use of this website at www.apricot.co.in (hereafter referred to as "the website"). You agree to accept and be bound by these terms and conditions by accessing the website and/or placing an order of purchase of jewellery. Regardless of whether or not you choose to register with us or place an order with us, you confirm your acceptance of these terms and conditions upon use of the website. "Jewellery" means the jewellery that is predesigned or jewellery set with diamonds and/or gemstones that are available for sale on our website. Please note that all Jewellery is sold on an "as is" basis.</p>
                    <p className="mb-5">1.2. You can access most of the pages of the website without registering your details with us. Certain areas of the website are only open to you if you register.</p>
                    <p className="mb-5">1.3. Please read and familiarize yourself with these terms and conditions and if you do not accept them, please do not use the website.</p>
                    <p className="mb-5">1.4. NOTE: This document constitutes an "electronic record" under the provisions of the Information Technology Act, 2000 and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                    <h3 className="text-[19px] mb-5 font-[700]">Your Obligations</h3>
                    <p className="mb-5">2.1. In these Terms and Conditions, and in the context of a registered user or where the context so requires, the term 'You' shall mean any natural or legal person who has agreed to become a member of the website by providing Registration Data while registering on the Website using the computer systems of the Website; has accepted the terms and conditions contained in this electronic record and has allocated himself a unique identification user name or "User ID" and "Password".</p>
                    <p className="mb-5">2.2. You accept that the website and/or its’ owners have the right to amend these terms and conditions at any time without prior notice to you and consequently you agree to review these terms and conditions periodically and/or prior to each online purchase of jewellery. Certain provisions of these terms and conditions may be superseded by expressly designated legal notices or terms located on particular pages of the website which will override these terms and conditions to that extent only. In that event, the other terms and conditions herein shall remain in full force. If you do not wish to accept any such expressly designated legal notices and conditions, you should not continue to use the website.</p>
                    <p className="mb-5">2.3. You agree that in no event shall the website or its’ owning company or any of its’ directors/owners/agents be liable for any direct, indirect, incidental, special or consequential damages arising out of or in any way connected with the use of the website or for the delay or inability to use the website, or for any information, products, and services obtained through the website, or otherwise arising out of the use of the website, whether based on contract or strict liability or any other law or otherwise.</p>

                  
                    <h3 className="text-[19px] mb-5 font-[700]">Registration & Other Obligations</h3>
                    <p className="mb-5">3.1. As a new Registered User, these Terms and Conditions shall be effective and binding upon your 'acceptance'. 'Acceptance' shall mean your affirmative action in filling your registration data and clicking on the ‘continue’ button as provided on the registration page. If you do not accept these terms and conditions, do not fill up your registration data or click "Continue" on the Registration page.</p>
                    <p className="mb-5">3.2. You recognize that your Registered Data is for the purpose of processing your online purchase order and for providing ancillary services or products that may be offered by  www.apricot from time to time. You authorize www.apricot to retain such data and to transmit the data to its various outlets/offices or to parties (whoever is/are contracted with  www.apricot) which provide such services or products, in whichever country they may be located. You acknowledge that the website and/or its chosen partners may contact you via email or other means for your order or changes or alterations to the order or promotional purposes.</p>
                    <p className="mb-5">3.3. You are responsible for maintaining the confidentiality of your User ID and Password and for restricting access to your computer, computer system and computer network, and you are responsible for all activities that occur under your User ID and Password.</p>
                    <p className="mb-5">3.4. You agree to provide accurate, true and complete updated information of yourself as requested for by www.apricot at the time of registration and/or from time to time. Should you provide any data or information which www.apricot has reason to believe to be false, inaccurate or incomplete, www.apricot shall have the right to terminate or suspend your account/membership and deny you access to the website.</p>
                    <h3 className="text-[19px] mb-5 font-[700]">USE OF INFORMATION COLLECTED</h3>

                    <p className="mb-5">Apricot Jewels owns all the information collected via the Website or applications installed on the website or native mobile applications. As applicable, the information collected by Apricot Jewels shall be used to:</p>
                    <ul className="ms-[30px] mb-5 list-disc">
                        <li >Contact you regarding the Website or native mobile applications and related news and services available on them;</li>
                        <li >Monitor and improve the Website or native mobile applications;</li>
                        <li >Calculate the number of visitors to the Website or native mobile applications and identify their geographical locations;</li>
                        <li >Update you on special offers available on the Website or native mobile applications and provide you with a better shopping experience. This includes sending emails about various offers on the website or native mobile applications. You may unsubscribe from such emails at any time.</li>
                    </ul>

                    <p className="mb-5">Some of your information may be shared with and used by third parties who require access to information, such as courier companies, credit card processing companies, vendors, etc., to enable them and Apricot Jewels to perform their duties and fulfill your order requirements. Apricot Jewels does not allow any unauthorized person or organization to use any information that Apricot Jewels may collect from you through the Website and native mobile applications. However, Apricot Jewels and our native mobile applications are not responsible for any information collected, shared, or used by any other third-party website or mobile applications due to your browser settings.</p>

                    <p className="mb-5">Apricot Jewels reserves the right to share any of your personal information to comply with subpoenas, court orders, or other legal processes. Your Personal Information may be disclosed per such subpoenas, court orders, or legal processes without prior notice to you.</p>
                    <p className="mb-5">Apricot Jewels may share collective information such as demographics and Website or mobile application usage statistics with our sponsors, advertisers, or other third parties (excluding Apricot Jewels' marketing partners and network providers). When this type of information is shared, such parties do not have access to your Personal Information. When you contact Apricot Jewels through any means, such as chat or email, Apricot Jewels reserves the right to include your email ID for marketing communications. You can unsubscribe from such communications at any time.</p>

                    <p className="mb-5">The Website and native mobile applications may contain links that lead you to other Websites or mobile applications. Please note that once you leave our Website or native mobile applications, you will be subject to the Privacy Policy of the other website or mobile application, and this Privacy Policy will no longer apply.</p>
                    <h3 className="text-[19px] mb-5 font-[700]">BY USING THE WEBSITE OR NATIVE MOBILE APPLICATIONS, YOU SIGNIFY YOUR AGREEMENT TO THE TERMS OF THIS PRIVACY POLICY. APRICOT JEWELS RESERVES THE RIGHT, IN OUR SOLE DISCRETION, TO CHANGE, MODIFY, ADD, OR DELETE PORTIONS OF THE TERMS OF THIS PRIVACY POLICY AT ANY TIME.</h3>

                    <p className="mb-5">If you have any questions about this Privacy Policy, please feel free to contact us through our Website or native mobile applications or write to us at apricotjewels0@gmail.com.</p>



                </div>
            </section>





            <Footer />
        </>

    )
}

export default AboutUs